### PR TITLE
fix: Fixes missing type declaration in downstream consumers

### PR DESCRIPTION
**Pull request by nib-bturner**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [guidelines](/okta/okta-oidc-middleware/blob/master/CONTRIBUTING.md#commit)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix (**OBVIOUS FIX**)
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Adding Tests
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation changes
- [ ] Other... Please describe:

## What is the current behavior?

Users are unable to consume the typescript types found in this package. This is due to the `./scripts/build.js` file not copying the `./types/` directory to `./dist`. Thus when the package is published, the types are missing for downstream consumers. See image below

image

Issue Number: N/A

## What is the new behavior?

Users are able to consume types.

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by tgfisher4** [comment]
@jaredperreault-okta @vijetmahabaleshwar-okta You look to have been active in this repo recently. I would like to consume `@okta/oidc-middleware` types but am currently unable due to the issue addressed here. Any chance we can get this reviewed/merged/fixed so TypeScript users like myself can consume the SDK's types?

**Comment by sgtsquiggs** [comment]
+1

I am currently having to pin @okta/oidc-middleware to
`github:okta/okta-oidc-middleware#834bc696bae21c1112d7c46063944e3e0dfb3666` due to this issue. The 5.2.0 release adds types but neglects to bundle them into the npm release.

**Comment by jaredperreault-okta** [comment]
@nib-bturner @tgfisher4 @sgtsquiggs `5.2.1` was just released, which contains the types in the output bundle

**Comment by jaredperreault-okta** [comment]
Merged in #75

**Pull request closed without merging**
