### PR TITLE
Fix 401 error in login route handler when login callback path is child of login path

### PR DESCRIPTION
**Pull request by denysoblohin-okta**
Resolves https://github.com/okta/okta-oidc-js/issues/207

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [guidelines](/okta/okta-oidc-middleware/blob/master/CONTRIBUTING.md#commit)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Adding Tests
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: [OKTA-262240](https://oktainc.atlassian.net/browse/OKTA-262240)

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by shuowu** [comment]
Can https://github.com/okta/okta-oidc-middleware/issues/20#issuecomment-528550857 be handled by this change?

**Comment by denysoblohin-okta** [comment]
@shuowu Can't reproduce error in #20 comment (and not sure about value of `APP_ROOT` for comment author, probably more info/code required about his project)

**Comment by shuowu** [comment]
Maybe try with a random root path, like `/root`. Or like what described in https://github.com/okta/okta-oidc-middleware/issues/20#issuecomment-551343166

**Comment by denysoblohin-okta** [comment]
Still can't reproduce with root path like described in https://github.com/okta/okta-oidc-middleware/issues/20#issuecomment-551343166

**Review by shuowu — APPROVED** [review]

**Review by shuowu-okta — APPROVED** [review]

**Pull request closed without merging**
